# Generated by Django 5.0.1 on 2024-01-06 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest_rate', models.FloatField(default=2.0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('paid', 'paid'), ('active', 'active')], default='pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('share', 'share'), ('loan', 'loan'), ('voluntary', 'voluntary'), ('penalty', 'penalty'), ('interest', 'interest')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_received', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
