# Generated by Django 5.0.1 on 2024-02-27 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_loans_amount_installment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='loans',
            options={'verbose_name_plural': 'Loans'},
        ),
        migrations.AddField(
            model_name='loans',
            name='issue_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.loans')),
            ],
            options={
                'verbose_name_plural': 'Installments',
            },
        ),
        migrations.CreateModel(
            name='SharesAndOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('share', 'share'), ('other', 'other')], default='share', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_received', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shares and Others',
            },
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
